export const Images = {
    appIcon: require('./images/app_icon.png'),
    defaultTeam: require('./images/group.png'),
    circleX: require('./images/cancel.png'),
    circleCheck: require('./images/check.png'),
    left: require('./images/left.png'),
    right: require('./images/right.png'),
    option: require('./images/option.png'),
    pencil: require('./images/pencil.png'),
    defaultProfile: require('./images/person.png'),
    radioBlue: require('./images/radio_blue.png'),
    radioGray: require('./images/radio_gray.png'),
    radioGreen: require('./images/radio_green.png'),
    radioRed: require('./images/radio_red.png'),
}